export interface Solution {
  slug: string
  acronym: string
  name: string
  subtitle: string
  tagline: string
  overview: string
  description: string
  features: string[]
  benefits: { title: string; description: string }[]
  icon: string
  color: string
  bgColor: string
}

export const solutions: Solution[] = [
  {
    slug: 'bpm',
    acronym: 'APM',
    name: 'Advanced Process Management',
    subtitle: 'Gestão e automação de processos',
    tagline: 'Processos mapeados, automatizados e sob controle total',
    overview: 'Muitas empresas perdem tempo com processos que só existem na cabeça das pessoas: aprovações por e-mail, tarefas esquecidas e nenhuma visibilidade de onde cada solicitação está. O APM da Softeum resolve isso permitindo modelar visualmente cada fluxo em BPMN 2.0, definir responsáveis por etapa, configurar gatilhos automáticos e acompanhar cada instância em tempo real. A plataforma se integra com ERPs e sistemas legados para que os dados fluam sem retrabalho manual. O resultado é uma operação padronizada, rastreável e com até 60% menos tempo gasto em atividades repetitivas.',
    description:
      'Transforme a forma como sua empresa opera com o APM da Softeum. Mapeie, automatize e otimize processos de ponta a ponta, eliminando gargalos e aumentando a eficiência operacional com total visibilidade do fluxo de trabalho.',
    features: [
      'Modelagem visual de processos (BPMN 2.0)',
      'Automação de fluxos de trabalho',
      'Monitoramento em tempo real',
      'Integração com sistemas legados e ERPs',
      'Análise de desempenho e KPIs de processo',
      'Gestão de formulários dinâmicos',
      'Notificações e alertas automáticos',
      'Versionamento e histórico de processos',
      'Simulação e otimização de processos',
      'API e conectores prontos para integração',
    ],
    benefits: [
      { title: 'Eficiência Operacional', description: 'Redução de até 60% no tempo de execução de processos com automação inteligente.' },
      { title: 'Visibilidade Total', description: 'Acompanhe cada etapa em tempo real com dashboards e relatórios detalhados.' },
      { title: 'Conformidade', description: 'Padronização de atividades garantindo conformidade com normas e regulações.' },
      { title: 'Decisão Baseada em Dados', description: 'Analytics avançado para identificar gargalos e oportunidades de melhoria.' },
    ],
    icon: 'GitBranch',
    color: 'from-blue-500 to-cyan-500',
    bgColor: 'rgba(59,130,246,0.1)',
  },
  {
    slug: 'cpm',
    acronym: 'SPM',
    name: 'Strategic Performance Management',
    subtitle: 'Estratégia, indicadores e metas',
    tagline: 'Estratégia que se traduz em resultado mensurável',
    overview: 'É comum que a estratégia da liderança se perca no caminho até a operação: metas ficam em apresentações, indicadores são atualizados manualmente e ninguém sabe ao certo se a empresa está no rumo certo. O SPM da Softeum conecta planejamento estratégico e execução em uma única plataforma, onde você define OKRs, KPIs e metas corporativas e as desdobre em cascata para times e áreas. Dashboards executivos são atualizados automaticamente e alertas de desvio avisam quando algo foge do planejado. Com relatórios gerenciais prontos, o board tem visibilidade completa do desempenho da empresa sem depender de planilhas manuais.',
    description:
      'Alinhe estratégia e execução com o SPM da Softeum. Defina objetivos, monitore indicadores-chave e gerencie metas corporativas com visibilidade em todos os níveis da organização, do operacional ao conselho.',
    features: [
      'Planejamento estratégico e Balanced Scorecard (BSC)',
      'Gestão de KPIs, OKRs e metas',
      'Desdobramento de metas em cascata',
      'Dashboards executivos e analíticos',
      'Ciclos de planejamento e orçamento',
      'Consolidação de dados corporativos',
      'Análise de variância e tendências',
      'Relatórios gerenciais automatizados',
      'Gestão de iniciativas estratégicas',
      'Integração com BI e fontes de dados',
    ],
    benefits: [
      { title: 'Alinhamento Estratégico', description: 'Conecta estratégia e operação em todos os níveis hierárquicos.' },
      { title: 'Visibilidade 360°', description: 'Painel unificado do desempenho corporativo em tempo real.' },
      { title: 'Planejamento Ágil', description: 'Ciclos de planejamento mais rápidos e adaptáveis às mudanças do mercado.' },
      { title: 'Cultura de Resultados', description: 'Engajamento de equipes com metas claras e acompanhamento contínuo.' },
    ],
    icon: 'Target',
    color: 'from-purple-500 to-pink-500',
    bgColor: 'rgba(168,85,247,0.1)',
  },
  {
    slug: 'qms',
    acronym: 'QMP',
    name: 'Quality Management Platform',
    subtitle: 'Gestão da Qualidade',
    tagline: 'Qualidade rastreável em cada etapa do processo',
    overview: 'Empresas que buscam certificações ISO ou precisam manter padrões rígidos de qualidade enfrentam o desafio de registrar, tratar e comprovar cada ocorrência com evidências auditáveis. O QMP da Softeum centraliza não conformidades, ações corretivas e preventivas (CAPA), auditorias internas e documentação de qualidade em um único sistema integrado. Cada ocorrência é registrada, analisada pela causa raiz e acompanhada até a resolução, com prazo e responsável definidos. Isso reduz o custo de não conformidade, acelera a obtenção de certificações e cria uma cultura de melhoria contínua baseada em dados reais.',
    description:
      'Garanta a excelência dos seus produtos e serviços com o QMP da Softeum. Gerencie não conformidades, ações corretivas, auditorias e documentação de qualidade em um único sistema integrado para certificações ISO.',
    features: [
      'Gestão de não conformidades (NC)',
      'Ações corretivas e preventivas (CAPA)',
      'Planejamento e execução de auditorias',
      'Controle de documentos e registros de qualidade',
      'Gestão de indicadores de qualidade',
      'Calibração de instrumentos e equipamentos',
      'Análise de causa raiz (5 Porquês, Ishikawa)',
      'Suporte a ISO 9001, ISO 14001, ISO 45001',
      'Gestão de reclamações de clientes',
      'Planos de controle e inspeção',
    ],
    benefits: [
      { title: 'Menos Retrabalho', description: 'Redução significativa de desperdício e custos de não conformidade.' },
      { title: 'Certificações ISO', description: 'Sistema projetado para facilitar obtenção e manutenção de certificações.' },
      { title: 'Melhoria Contínua', description: 'Ciclos de PDCA estruturados para evolução constante dos processos.' },
      { title: 'Satisfação do Cliente', description: 'Rastreabilidade completa garantindo produtos e serviços de excelência.' },
    ],
    icon: 'CheckCircle2',
    color: 'from-green-500 to-emerald-500',
    bgColor: 'rgba(34,197,94,0.1)',
  },
  {
    slug: 'grc',
    acronym: 'CGR',
    name: 'Compliance, Governance & Risk',
    subtitle: 'Governança, riscos e compliance',
    tagline: 'Governança que protege e gera confiança',
    overview: 'Crescer como empresa exige governança sólida: controles internos eficazes, gestão de riscos estruturada e conformidade com regulações em constante mudança. O CGR da Softeum integra esses três pilares em uma visão única para o board e para as equipes de compliance, com gestão de riscos corporativos, monitoramento de controles internos, canal de denúncias e due diligence de fornecedores, tudo com rastreabilidade completa. Relatórios regulatórios gerados automaticamente reduzem o tempo de auditoria e eliminam a dependência de planilhas. Com isso, sua empresa fortalece a credibilidade perante investidores, reguladores e parceiros de negócio.',
    description:
      'Fortaleça a governança corporativa e assegure a conformidade regulatória com o CGR da Softeum. Gerencie riscos, controles internos e obrigações legais de forma integrada e transparente para todo o board.',
    features: [
      'Gestão de riscos corporativos integrada',
      'Controles internos e conformidade SOX',
      'Monitoramento de compliance regulatório',
      'Gestão de políticas e normas internas',
      'Programa de integridade e ética empresarial',
      'Canal de denúncias (whistleblowing)',
      'Due diligence de terceiros e fornecedores',
      'Relatórios regulatórios automatizados',
      'Matriz de controles e responsabilidades',
      'Gestão de conflito de interesses',
    ],
    benefits: [
      { title: 'Proteção Regulatória', description: 'Redução da exposição a riscos legais, multas e sanções regulatórias.' },
      { title: 'Cultura de Integridade', description: 'Programa estruturado de compliance que fortalece a ética organizacional.' },
      { title: 'Controles Eficientes', description: 'Automatização da gestão de controles com evidências rastreáveis.' },
      { title: 'Transparência', description: 'Relatórios claros para conselho, auditores e reguladores.' },
    ],
    icon: 'Scale',
    color: 'from-amber-500 to-orange-500',
    bgColor: 'rgba(245,158,11,0.1)',
  },
  {
    slug: 'erm',
    acronym: 'IRM',
    name: 'Integrated Risk Management',
    subtitle: 'Gestão Integrada de Riscos',
    tagline: 'Riscos identificados antes de virarem crise',
    overview: 'Toda empresa enfrenta riscos, mas poucas conseguem enxergá-los de forma consolidada antes que se tornem crises. O IRM da Softeum cria um universo de riscos corporativos unificado, classificado por probabilidade e impacto, com mapas de calor e indicadores de risco (KRI) atualizados em tempo real. Baseado nos frameworks COSO e ISO 31000, o sistema permite definir apetite ao risco, criar planos de mitigação e monitorar a eficácia de cada ação tomada. Com isso, a tomada de decisão estratégica deixa de ser intuitiva e passa a ser fundamentada em dados, cenários e evidências concretas.',
    description:
      'Identifique, avalie e mitigue riscos corporativos com uma visão holística do ambiente de negócios. O IRM da Softeum conecta riscos estratégicos, operacionais, financeiros e de conformidade em uma única visão integrada.',
    features: [
      'Identificação e categorização de riscos corporativos',
      'Matriz de risco (probabilidade × impacto)',
      'Planos de tratamento e mitigação de riscos',
      'Indicadores de risco (KRI) em tempo real',
      'Relatórios para Board, Comitês e Auditoria',
      'Frameworks COSO e ISO 31000',
      'Mapas de calor e heat maps de risco',
      'Gestão de apetite e tolerância ao risco',
      'Cenários de estresse e stress testing',
      'Consolidação do universo de riscos',
    ],
    benefits: [
      { title: 'Visão Integrada', description: 'Todos os riscos corporativos consolidados em um único painel executivo.' },
      { title: 'Decisões Seguras', description: 'Suporte à tomada de decisão estratégica com base em dados de risco.' },
      { title: 'Menos Crises', description: 'Identificação proativa de ameaças antes que se tornem incidentes críticos.' },
      { title: 'Proteção de Valor', description: 'Salvaguarda dos ativos, reputação e valor da organização.' },
    ],
    icon: 'Shield',
    color: 'from-red-500 to-rose-500',
    bgColor: 'rgba(239,68,68,0.1)',
  },
  {
    slug: 'esg',
    acronym: 'ESG',
    name: 'Environmental, Social & Governance',
    subtitle: 'Gestão ESG',
    tagline: 'Sustentabilidade mensurável, auditável e atrativa para investidores',
    overview: 'Investidores, clientes e reguladores exigem cada vez mais transparência sobre o desempenho ambiental, social e de governança das empresas, e ter boas intenções sem dados concretos não é suficiente. O ESG da Softeum estrutura toda essa agenda com informações confiáveis e rastreáveis: controle do inventário de emissões pelo GHG Protocol, monitoramento de indicadores GRI e SASB, gestão de programas sociais e geração automática de relatórios de sustentabilidade. Com um painel ESG dedicado para investidores e stakeholders, sua empresa demonstra comprometimento real com o desenvolvimento responsável. Além disso, uma posição ESG sólida amplia o acesso a linhas de crédito sustentáveis e fortalece a reputação no mercado.',
    description:
      'Estruture e reporte sua agenda ESG com dados confiáveis e rastreáveis. A plataforma conecta indicadores ambientais, sociais e de governança, facilitando a divulgação para investidores, reguladores e stakeholders.',
    features: [
      'Inventário de emissões de carbono (GHG Protocol)',
      'Gestão de metas e compromissos ESG',
      'Indicadores GRI, SASB, TCFD e CSRD',
      'Relatório de sustentabilidade automatizado',
      'Gestão de programas e impacto social',
      'Diversidade, equidade e inclusão (DEI)',
      'Supply chain sustentável e responsável',
      'Due diligence ambiental e social',
      'Cálculo de pegada de carbono',
      'Painel ESG para investidores',
    ],
    benefits: [
      { title: 'Acesso a Capital ESG', description: 'Atração de investidores e fundos com foco em sustentabilidade.' },
      { title: 'Conformidade Global', description: 'Aderência a regulações e frameworks internacionais de reporte.' },
      { title: 'Reputação', description: 'Posicionamento como empresa responsável perante clientes e sociedade.' },
      { title: 'Impacto Real', description: 'Redução mensurável de impactos ambientais e sociais.' },
    ],
    icon: 'Leaf',
    color: 'from-teal-500 to-green-500',
    bgColor: 'rgba(20,184,166,0.1)',
  },
  {
    slug: 'ehsm',
    acronym: 'SSMA',
    name: 'Segurança, Saúde e Meio Ambiente',
    subtitle: 'Saúde, segurança e meio ambiente',
    tagline: 'Segurança do trabalho e meio ambiente como cultura da empresa',
    overview: 'Acidentes de trabalho, não conformidades ambientais e falta de controle sobre treinamentos de segurança são riscos que custam caro, tanto em vidas quanto em multas e paralisações de operação. O SSMA da Softeum digitaliza toda a gestão de segurança do trabalho, saúde ocupacional e licenciamento ambiental em uma plataforma acessível por qualquer dispositivo. Permissões de trabalho digitais, análise de risco prévia (APR, HAZOP), gestão de EPIs e indicadores em tempo real substituem processos em papel e planilhas desatualizadas, eliminando pontos cegos operacionais. O resultado é uma cultura de segurança mais forte, redução comprovada de acidentes e plena conformidade com NRs e a legislação ambiental vigente.',
    description:
      'Proteja pessoas, ativos e o meio ambiente com o SSMA da Softeum. Gerencie incidentes, riscos ocupacionais, programas de saúde e obrigações ambientais com total rastreabilidade e conformidade legal.',
    features: [
      'Gestão de incidentes, acidentes e quase-acidentes',
      'Análise de risco (APR, HAZOP, FMEA, JSA)',
      'Permissão de trabalho (PT) digital',
      'Gestão de EPIs e treinamentos de segurança',
      'Monitoramento e licenciamento ambiental',
      'Obrigações legais ambientais (FISPQ, RIMA)',
      'Indicadores de saúde ocupacional (PPRA, PCMSO)',
      'Planos de emergência e resposta a crises',
      'Inspeções de segurança com checklist digital',
      'Dashboards de performance de segurança e meio ambiente',
    ],
    benefits: [
      { title: 'Menos Acidentes', description: 'Redução de acidentes e doenças ocupacionais com gestão proativa de riscos.' },
      { title: 'Conformidade Legal', description: 'Aderência a NRs, CONAMA e legislação ambiental vigente.' },
      { title: 'Cultura de Segurança', description: 'Engajamento de colaboradores com programas estruturados de segurança.' },
      { title: 'Zero Passivo Ambiental', description: 'Controle rigoroso de obrigações e licenças ambientais.' },
    ],
    icon: 'HeartPulse',
    color: 'from-cyan-500 to-blue-500',
    bgColor: 'rgba(6,182,212,0.1)',
  },
  {
    slug: 'ecm',
    acronym: 'DCM',
    name: 'Digital Content Management',
    subtitle: 'Gestão digital de documentos e conteúdo',
    tagline: 'Documentos organizados, acessíveis e em conformidade com a LGPD',
    overview: 'Documentos físicos dispersos, versões desatualizadas circulando por e-mail e falta de controle sobre quem acessou o quê são problemas que custam tempo e criam riscos legais significativos. O DCM da Softeum centraliza o ciclo de vida completo de todos os documentos corporativos: do armazenamento com controle de versões até a assinatura digital e o descarte controlado por tabela de temporalidade. A pesquisa full-text encontra qualquer documento em segundos, e o controle de acesso granular garante que apenas as pessoas certas vejam cada informação. Integrado ao Microsoft 365 e Google Workspace, o sistema é plenamente conforme à LGPD e auditável a qualquer momento.',
    description:
      'Organize, proteja e acesse documentos corporativos com rapidez e segurança. O DCM da Softeum centraliza o ciclo de vida do conteúdo, do armazenamento à aprovação e descarte controlado, em conformidade com a LGPD.',
    features: [
      'Repositório centralizado e seguro de documentos',
      'Controle de versões e trilha de auditoria completa',
      'Fluxos de aprovação e assinatura digital',
      'Classificação e taxonomia com metadados',
      'Pesquisa avançada full-text por conteúdo',
      'Integração com Microsoft 365 e Google Workspace',
      'Tabela de temporalidade e descarte controlado',
      'Controle de acesso granular por perfil',
      'OCR e captura inteligente de documentos',
      'Conformidade LGPD e regulações setoriais',
    ],
    benefits: [
      { title: 'Sem Papel', description: 'Eliminação de documentos físicos com digitalização e armazenamento seguro.' },
      { title: 'Acesso Remoto', description: 'Documentos disponíveis de qualquer lugar com segurança e rastreabilidade.' },
      { title: 'Conformidade LGPD', description: 'Gestão do ciclo de vida de dados pessoais conforme legislação.' },
      { title: 'Produtividade', description: 'Redução de até 80% no tempo de busca e recuperação de documentos.' },
    ],
    icon: 'FileText',
    color: 'from-violet-500 to-purple-500',
    bgColor: 'rgba(139,92,246,0.1)',
  },
  {
    slug: 'esm',
    acronym: 'ISM',
    name: 'Integrated Service Management',
    subtitle: 'Central integrada de serviços e chamados',
    tagline: 'Atendimento interno rápido, rastreável e com SLA cumprido',
    overview: 'Quando cada área da empresa usa um canal diferente para abrir chamados, o resultado é atendimento lento, SLAs descumpridos e colaboradores frustrados com o suporte interno. O ISM da Softeum vai além do help desk de TI e cria uma central unificada de serviços para RH, Facilities, Financeiro e qualquer outra área, com um portal self-service intuitivo onde os colaboradores abrem, acompanham e avaliam chamados. SLAs são configurados por tipo de serviço com escalonamento automático, e a base de conhecimento com inteligência artificial sugere soluções antes mesmo de o chamado ser aberto. Relatórios de desempenho por área mostram exatamente onde estão os gargalos e como eliminá-los de forma contínua.',
    description:
      'Gerencie solicitações e incidentes de toda a empresa com uma central integrada. O ISM da Softeum vai além da TI, atendendo RH, Facilities, Financeiro e qualquer área de serviço com SLAs automatizados.',
    features: [
      'Portal de serviços self-service para colaboradores',
      'Gestão de incidentes, problemas e mudanças',
      'Catálogo de serviços configurável por área',
      'SLAs e OLAs automatizados com escalonamento',
      'Base de conhecimento (KB) inteligente',
      'Gestão de mudanças (Change Management ITIL)',
      'Integração com ITIL 4 e frameworks ágeis',
      'Chatbot e automação de atendimento com IA',
      'Pesquisa de satisfação (NPS e CSAT)',
      'Relatórios de desempenho e SLA por área',
    ],
    benefits: [
      { title: 'Resolução Rápida', description: 'Redução do tempo de resolução de chamados com automação e base de conhecimento.' },
      { title: 'Satisfação Interna', description: 'Experiência superior para colaboradores com atendimento ágil e transparente.' },
      { title: 'SLA Cumprido', description: 'Monitoramento em tempo real e escalonamento automático de chamados críticos.' },
      { title: 'Visibilidade Operacional', description: 'Dashboards de desempenho por área de serviço e equipe.' },
    ],
    icon: 'Headphones',
    color: 'from-sky-500 to-indigo-500',
    bgColor: 'rgba(14,165,233,0.1)',
  },
  {
    slug: 'ppm',
    acronym: 'PPS',
    name: 'Project Portfolio System',
    subtitle: 'Gestão de projetos e portfólio',
    tagline: 'Projetos entregues no prazo, no orçamento e alinhados à estratégia',
    overview: 'Gerenciar vários projetos ao mesmo tempo, com diferentes equipes, orçamentos e cronogramas, sem uma visão unificada do portfólio, é um dos maiores desafios de qualquer PMO. O PPS da Softeum entrega controle total de cronograma, recursos e custos de todos os projetos simultaneamente, com Gráfico de Gantt interativo, gestão de capacidade de equipe e controle orçamentário em tempo real. Metodologias ágeis e preditivas coexistem no mesmo ambiente, e portões de governança garantem que nenhum projeto avance sem as aprovações necessárias. Com dashboards de portfólio, gestores e executivos tomam decisões de priorização com base em dados concretos, não em percepções.',
    description:
      'Planeje, priorize e execute projetos com total controle de recursos, cronogramas e orçamentos. O PPS da Softeum oferece visibilidade de portfólio para decisões estratégicas de investimento e alocação de recursos.',
    features: [
      'Gestão de portfólio e priorização estratégica',
      'Cronograma interativo e Gráfico de Gantt',
      'Gestão de recursos e capacidade da equipe',
      'Controle de custos e orçamento de projeto',
      'Gestão de riscos e dependências de projeto',
      'Metodologias ágeis (Scrum, Kanban) e preditivas',
      'Relatórios de status e indicadores RAG',
      'Governança e portão de aprovação de projetos',
      'Gestão de benefícios e valor entregue',
      'Integração com ferramentas de desenvolvimento',
    ],
    benefits: [
      { title: 'Projetos no Prazo', description: 'Maior taxa de entrega de projetos dentro do prazo e orçamento planejados.' },
      { title: 'Portfólio Estratégico', description: 'Alinhamento dos projetos às prioridades e estratégias corporativas.' },
      { title: 'Recursos Otimizados', description: 'Visibilidade completa da capacidade e alocação de recursos humanos.' },
      { title: 'Governança Robusta', description: 'Portões de decisão e aprovação estruturados para cada fase do projeto.' },
    ],
    icon: 'Kanban',
    color: 'from-orange-500 to-amber-500',
    bgColor: 'rgba(249,115,22,0.1)',
  },
  {
    slug: 'plm',
    acronym: 'PCM',
    name: 'Product Cycle Management',
    subtitle: 'Ciclo de vida do produto',
    tagline: 'Do conceito ao mercado sem perder rastreabilidade',
    overview: 'Empresas que desenvolvem produtos físicos enfrentam um desafio constante: manter engenharia, qualidade e supply chain alinhados em torno de uma única versão atualizada do produto, sem retrabalho e sem informação desencontrada. O PCM da Softeum é essa fonte única de verdade, integrando especificações, estrutura de produto, mudanças de engenharia, documentos técnicos e aprovações em workflows automatizados. Cada alteração passa por um processo controlado de aprovação com histórico completo e notificação para todas as áreas impactadas. O resultado é menos retrabalho de engenharia, maior velocidade de lançamento de produtos e rastreabilidade completa de cada componente e versão.',
    description:
      'Gerencie o ciclo completo dos seus produtos, da concepção ao descontinuamento. O PCM da Softeum integra engenharia, qualidade, supply chain e marketing em torno de uma única fonte de verdade do produto.',
    features: [
      'Gestão de especificações e requisitos do produto',
      'Estrutura de produto (BOM: Bill of Materials)',
      'Gestão de mudanças de engenharia (ECO/ECR)',
      'Controle de documentos técnicos e desenhos',
      'Workflows de aprovação e desenvolvimento',
      'Gestão de variantes e configurações de produto',
      'Rastreabilidade de componentes e materiais',
      'Integração com ERP, CAD e sistemas de engenharia',
      'Gestão de fornecedores de componentes',
      'Ciclo de vida regulatório e compliance de produto',
    ],
    benefits: [
      { title: 'Time-to-Market', description: 'Redução do tempo de lançamento de novos produtos com processos ágeis.' },
      { title: 'Menos Retrabalho', description: 'Redução de erros de engenharia com gestão rigorosa de mudanças.' },
      { title: 'Rastreabilidade', description: 'Histórico completo de cada versão e componente do produto.' },
      { title: 'Colaboração', description: 'Engenharia, qualidade e supply chain trabalhando com a mesma informação.' },
    ],
    icon: 'Package',
    color: 'from-lime-500 to-green-500',
    bgColor: 'rgba(132,204,22,0.1)',
  },
  {
    slug: 'slm',
    acronym: 'VMS',
    name: 'Vendor Management System',
    subtitle: 'Gestão de fornecedores e terceiros',
    tagline: 'Fornecedores qualificados, monitorados e em conformidade',
    overview: 'Terceirizar sem visibilidade é um risco real: fornecedores não qualificados, entregas fora do prazo e falta de conformidade regulatória criam vulnerabilidades que podem comprometer toda a operação da empresa. O VMS da Softeum entrega uma visão completa de cada fornecedor, desde a qualificação inicial com due diligence de compliance, finanças e ESG, até o monitoramento contínuo de desempenho por scorecard. Um portal self-service permite que os próprios fornecedores atualizem documentos e respondam avaliações, reduzindo a carga operacional da equipe interna. Com alertas de risco de supply chain e planos de desenvolvimento ativo, sua cadeia de fornecimento fica mais resiliente e previsível.',
    description:
      'Qualifique, monitore e desenvolva sua cadeia de fornecedores com visibilidade completa. O VMS da Softeum reduz riscos de supply chain e garante conformidade de terceiros com políticas internas e regulações externas.',
    features: [
      'Cadastro e qualificação de fornecedores',
      'Due diligence de compliance, financeiro e ESG',
      'Avaliação de desempenho por scorecard',
      'Gestão de contratos de fornecimento',
      'Monitoramento de SLAs e entregas de fornecedores',
      'Planos de desenvolvimento de fornecedores (SDP)',
      'Gestão de risco de supply chain',
      'Portal do fornecedor self-service',
      'Homologação e recertificação periódica',
      'Integração com ERP e procurement',
    ],
    benefits: [
      { title: 'Risco Controlado', description: 'Visibilidade dos riscos de terceiros com monitoramento contínuo.' },
      { title: 'Qualidade de Fornecimento', description: 'Desenvolvimento ativo de fornecedores para melhoria de desempenho.' },
      { title: 'Fornecedores Conformes', description: 'Garantia de aderência às políticas internas e regulações do setor.' },
      { title: 'Supply Chain Resiliente', description: 'Cadeia de suprimentos mais robusta e com menos surpresas.' },
    ],
    icon: 'Truck',
    color: 'from-yellow-500 to-amber-500',
    bgColor: 'rgba(234,179,8,0.1)',
  },
  {
    slug: 'eam',
    acronym: 'AMM',
    name: 'Asset & Maintenance Management',
    subtitle: 'Gestão de ativos e manutenção',
    tagline: 'Ativos funcionando mais, custando menos e com vida útil estendida',
    overview: 'Equipamentos parados por falhas inesperadas geram perdas de produção, custos elevados de manutenção corretiva e riscos à segurança que poderiam ter sido evitados com planejamento adequado. O AMM da Softeum controla o ciclo de vida completo dos ativos físicos, do cadastro e hierarquia até as ordens de serviço mobile, gestão de peças de reposição e planejamento anual de manutenção. Integrado a sensores IoT e sistemas SCADA, o sistema detecta anomalias antecipadamente e aciona manutenção preditiva antes que o problema cause uma parada. Os indicadores OEE, MTBF e MTTR em tempo real mostram exatamente onde focar para maximizar disponibilidade e reduzir custos operacionais.',
    description:
      'Maximize a disponibilidade e vida útil dos seus ativos físicos com o AMM da Softeum. Planeje manutenções preventivas, gerencie ordens de serviço e controle o ciclo de vida completo dos ativos industriais.',
    features: [
      'Cadastro e hierarquia de ativos físicos',
      'Manutenção preventiva e preditiva (PdM)',
      'Ordens de serviço (OS) digitais e mobile',
      'Gestão de peças de reposição e estoque MRO',
      'Indicadores de manutenção (OEE, MTBF, MTTR)',
      'Inspeções técnicas com checklist digital',
      'Controle de garantias e contratos de manutenção',
      'Integração com IoT, sensores e SCADA',
      'Planejamento de manutenção anual (PMA)',
      'Gestão do ciclo de vida e valor de ativo',
    ],
    benefits: [
      { title: 'Maior Disponibilidade', description: 'Aumento da disponibilidade de equipamentos com manutenção proativa.' },
      { title: 'Menos Paradas', description: 'Redução de paradas não planejadas e perdas de produção.' },
      { title: 'Vida Útil Estendida', description: 'Extensão da vida útil dos ativos com manutenção baseada em condição.' },
      { title: 'Custos Otimizados', description: 'Redução dos custos de manutenção com planejamento inteligente de recursos.' },
    ],
    icon: 'Wrench',
    color: 'from-slate-400 to-gray-500',
    bgColor: 'rgba(148,163,184,0.1)',
  },
  {
    slug: 'hdm',
    acronym: 'TDM',
    name: 'Talent Development Management',
    subtitle: 'Desenvolvimento de talentos e competências',
    tagline: 'Talentos desenvolvidos, engajados e preparados para crescer',
    overview: 'Desenvolver pessoas de forma estruturada vai muito além de organizar treinamentos: exige mapear competências, identificar lacunas, criar planos de desenvolvimento individuais e acompanhar a evolução de cada colaborador ao longo do tempo. O TDM da Softeum integra tudo isso em uma única plataforma com LMS, avaliação de desempenho 360 graus, gestão de sucessão e controle de treinamentos obrigatórios com evidências auditáveis para compliance. Os gestores enxergam em tempo real quais competências a equipe já possui e quais precisam ser desenvolvidas para atingir os objetivos do negócio. Com trilhas de aprendizagem personalizadas por função, os colaboradores crescem de forma alinhada à estratégia da empresa e o índice de retenção de talentos aumenta de forma mensurável.',
    description:
      'Desenvolva o capital humano da sua organização com o TDM da Softeum. Plataforma integrada de gestão de competências, trilhas de aprendizagem, avaliação de desempenho e planos de desenvolvimento individual.',
    features: [
      'Mapeamento de competências e CHA',
      'Trilhas de desenvolvimento personalizadas',
      'LMS integrado (Learning Management System)',
      'Avaliação de desempenho 90°, 180° e 360°',
      'Plano de desenvolvimento individual (PDI)',
      'Gestão de treinamentos obrigatórios e regulatórios',
      'Indicadores de T&D e efetividade de treinamento',
      'Gestão de sucessão e talentos-chave',
      'Portal do colaborador para autodesenvolvimento',
      'Integração com HCM e sistemas de RH',
    ],
    benefits: [
      { title: 'Competências Críticas', description: 'Desenvolvimento acelerado das competências essenciais da organização.' },
      { title: 'Retenção de Talentos', description: 'Redução do turnover com planos de carreira claros e investimento em pessoas.' },
      { title: 'Treinamentos Conformes', description: 'Controle rigoroso de treinamentos obrigatórios com evidências auditáveis.' },
      { title: 'Cultura de Aprendizagem', description: 'Estímulo ao desenvolvimento contínuo e crescimento profissional.' },
    ],
    icon: 'GraduationCap',
    color: 'from-fuchsia-500 to-pink-500',
    bgColor: 'rgba(217,70,239,0.1)',
  },
  {
    slug: 'icm',
    acronym: 'IEM',
    name: 'Innovation & Evolution Management',
    subtitle: 'Gestão de inovação e transformação',
    tagline: 'Inovação estruturada e mudanças que realmente acontecem',
    overview: 'Ideias surgem em todos os níveis da empresa, mas sem um processo estruturado a maioria se perde antes de virar resultado real. O IEM da Softeum transforma essas ideias em um portfólio de inovação gerenciado, com estágios de maturidade, critérios de avaliação e responsáveis definidos para cada iniciativa. Ao mesmo tempo, o módulo de gestão de transformação organizacional planeja e monitora a adoção de mudanças com análise de impacto, planos de comunicação e engajamento de stakeholders. Com isso, inovações chegam ao mercado mais rápido e transformações críticas encontram menos resistência interna, aumentando a taxa de sucesso das iniciativas.',
    description:
      'Estruture sua jornada de inovação e gerencie transformações organizacionais com efetividade. O IEM da Softeum conecta ideias à implementação com portfólio de inovação e ferramentas de gestão de mudança.',
    features: [
      'Banco de ideias colaborativo e crowdsourcing',
      'Portfólio de inovação com estágios de maturidade',
      'Plano de gestão de transformação organizacional',
      'Análise de impacto e mapeamento de resistência',
      'Comunicação e engajamento de stakeholders',
      'Monitoramento de adoção e sustentação da mudança',
      'Design thinking e metodologias ágeis de inovação',
      'Indicadores de inovação e ROI de P&D',
      'Colaboração com ecossistema externo (startups)',
      'Gestão de propriedade intelectual (PI)',
    ],
    benefits: [
      { title: 'Cultura de Inovação', description: 'Estrutura que transforma ideias em resultados de negócio concretos.' },
      { title: 'Mudanças Bem-Sucedidas', description: 'Maior taxa de sucesso em projetos de transformação organizacional.' },
      { title: 'Engajamento', description: 'Colaboradores engajados e protagonistas das mudanças da empresa.' },
      { title: 'Velocidade', description: 'Implementação mais rápida de iniciativas com menor resistência.' },
    ],
    icon: 'Lightbulb',
    color: 'from-yellow-400 to-orange-500',
    bgColor: 'rgba(250,204,21,0.1)',
  },
  {
    slug: 'cwm',
    acronym: 'TCM',
    name: 'Team Collaboration Management',
    subtitle: 'Gestão de trabalho colaborativo em equipe',
    tagline: 'Equipes alinhadas e produtivas, trabalhem de onde for',
    overview: 'Equipes que trabalham com múltiplas ferramentas desconectadas perdem tempo alternando entre contextos, duplicam informações e ficam sem visibilidade do que cada pessoa está fazendo e entregando. O TCM da Softeum centraliza tarefas, projetos, documentos colaborativos e comunicação de equipe em um único ambiente integrado, eliminando os silos de informação. Boards Kanban, sprints ágeis e automações de lembretes reduzem o trabalho administrativo e permitem que as equipes foquem nas entregas que realmente importam. Integrado ao Slack, Microsoft Teams e e-mail, o TCM funciona para equipes presenciais, remotas e híbridas, mantendo todo o histórico de decisões e progresso acessível a qualquer momento.',
    description:
      'Conecte equipes e centralize o trabalho colaborativo com o TCM da Softeum. Gerencie tarefas, projetos e comunicação em um ambiente integrado que aumenta a produtividade em equipes híbridas.',
    features: [
      'Gestão de tarefas individuais e em equipe',
      'Boards Kanban, listas e visualizações flexíveis',
      'Colaboração em documentos e wikis em tempo real',
      'Gestão de sprints e iterações ágeis',
      'Comunicação integrada por projeto e equipe',
      'Integração com Slack, Microsoft Teams e e-mail',
      'Relatórios de produtividade e entregas',
      'Automação de tarefas e lembretes inteligentes',
      'Compartilhamento seguro com externos',
      'App mobile para trabalho remoto',
    ],
    benefits: [
      { title: 'Produtividade', description: 'Equipes mais produtivas com menos reuniões e mais entregas.' },
      { title: 'Sem Silos', description: 'Informação centralizada acessível a todos os membros da equipe.' },
      { title: 'Visibilidade', description: 'Progresso de cada tarefa e projeto visível em tempo real para gestores.' },
      { title: 'Colaboração Híbrida', description: 'Trabalho eficiente independente do local ou fuso horário da equipe.' },
    ],
    icon: 'Users2',
    color: 'from-indigo-500 to-blue-500',
    bgColor: 'rgba(99,102,241,0.1)',
  },
  {
    slug: 'pedido-flow',
    acronym: 'Pedido Flow',
    name: 'Pedido Flow',
    subtitle: 'Captura automática de pedidos para o ERP',
    tagline: 'Pedidos de e-mail e WhatsApp direto no ERP, sem digitação manual',
    overview: 'Receber pedidos por e-mail e WhatsApp e precisar digitá-los manualmente no ERP é um processo lento, caro e sujeito a erros que afeta diretamente a velocidade do ciclo de vendas e a satisfação do cliente. O Pedido Flow usa inteligência artificial para ler automaticamente cada pedido recebido nesses canais, extrair itens, quantidades, preços e dados do cliente, e lançar tudo diretamente no ERP sem nenhuma intervenção humana. O sistema opera 24 horas por dia, 7 dias por semana, e envia atualizações de status automáticas para cada cliente após a confirmação do pedido. Com isso, a equipe de vendas deixa de ser operacional e passa a focar em relacionamento e estratégia, processando o triplo de pedidos com a mesma estrutura atual.',
    description:
      'Automatize a captura de pedidos recebidos por e-mail e WhatsApp e integre diretamente ao seu ERP. O Pedido Flow elimina retrabalho manual, reduz erros humanos e acelera o ciclo de vendas com inteligência artificial.',
    features: [
      'Leitura automática de e-mails de pedido com IA',
      'Integração com WhatsApp Business API',
      'Extração inteligente de itens, quantidades e preços',
      'Validação e normalização automática de dados',
      'Integração com ERPs (SAP, TOTVS, Oracle, Sankhya e outros)',
      'Notificações de status automáticas ao cliente',
      'Painel de acompanhamento de pedidos em tempo real',
      'Histórico e auditoria completa de pedidos',
      'Tratamento de exceções com revisão humana',
      'Relatórios de volume e tempo de processamento',
    ],
    benefits: [
      { title: 'Zero Digitação Manual', description: 'Eliminação completa da entrada manual de pedidos com automação IA.' },
      { title: 'Menos Erros', description: 'Redução de erros de digitação e inconsistências no processo de pedidos.' },
      { title: 'Operação 24/7', description: 'Processamento de pedidos ininterrupto, inclusive fora do horário comercial.' },
      { title: 'Cliente Satisfeito', description: 'Respostas mais rápidas e status automático para cada pedido recebido.' },
    ],
    icon: 'Mail',
    color: 'from-emerald-500 to-teal-500',
    bgColor: 'rgba(16,185,129,0.1)',
  },
  {
    slug: 'csd',
    acronym: 'CSD',
    name: 'Custom System Development',
    subtitle: 'Desenvolvimento de sistemas sob medida',
    tagline: 'Seu sistema, do jeito que o seu negócio precisa',
    overview: 'Nem sempre um sistema de prateleira resolve o problema: quando o processo da empresa é muito específico, adaptar o negócio ao software gera perdas de eficiência, resistência interna e funcionalidades que nunca serão usadas. O CSD da Softeum desenvolve sistemas web e mobile do zero, construídos exatamente para o fluxo de trabalho da sua empresa, com UX pensada desde o primeiro rascunho. O processo começa com um discovery estruturado para entender necessidades e contexto, passa pela arquitetura, design e desenvolvimento ágil em sprints com entregas funcionais desde as primeiras semanas. O código-fonte é 100% seu, a documentação é completa e o suporte pós-entrega garante que o sistema evolua junto com o negócio.',
    description:
      'Transforme sua ideia em um sistema real, construído do zero para o seu negócio. O CSD reúne arquitetura de software, design de UX e desenvolvimento ágil para entregar soluções digitais sob medida.',
    features: [
      'Levantamento de requisitos e discovery de produto',
      'Arquitetura de software escalável e segura',
      'Desenvolvimento web e mobile personalizado',
      'APIs e integrações com sistemas e ERPs existentes',
      'Design UX/UI centrado no usuário',
      'Metodologia ágil com entregas iterativas (sprints)',
      'Testes automatizados e garantia de qualidade (QA)',
      'DevOps, CI/CD e deploy em cloud (AWS, Azure, GCP)',
      'Manutenção evolutiva e suporte pós-entrega',
      'Documentação técnica e de usuário completa',
    ],
    benefits: [
      { title: 'Feito Para Você', description: 'Sistema 100% aderente ao seu processo, sem adaptações ou workarounds.' },
      { title: 'Integração Total', description: 'Conectamos o novo sistema a tudo que sua empresa já usa.' },
      { title: 'Código Seu', description: 'Propriedade total do código-fonte e da solução desenvolvida.' },
      { title: 'Entrega Ágil', description: 'Primeiras versões funcionais em semanas com metodologia incremental.' },
    ],
    icon: 'Code2',
    color: 'from-blue-500 to-violet-600',
    bgColor: 'rgba(99,102,241,0.1)',
  },
  {
    slug: 'ia-first',
    acronym: 'IA First',
    name: 'IA First',
    subtitle: 'Projetos personalizados e automação com IA',
    tagline: 'Inteligência artificial aplicada aos desafios reais do seu negócio',
    overview: 'Inteligência artificial deixou de ser diferencial para se tornar necessidade competitiva, mas implementar IA de forma eficaz exige muito mais do que integrar uma API ou testar um chatbot genérico. O IA First da Softeum desenvolve projetos de IA sob medida para cada negócio: assistentes virtuais com LLMs como Claude e GPT-4, modelos de análise preditiva com machine learning, automação inteligente de processos e visão computacional aplicada à operação. Cada projeto começa com uma consultoria de estratégia de IA para identificar onde o impacto é maior e termina com operacionalização completa em produção, com monitoramento contínuo dos modelos. O resultado são processos mais rápidos, decisões mais precisas e vantagem competitiva real e mensurável.',
    description:
      'Desenvolvemos projetos de Inteligência Artificial sob medida para o seu negócio. Da automação de processos à análise preditiva, o IA First traz o poder da IA generativa e do machine learning para resolver desafios reais da sua empresa.',
    features: [
      'Automação inteligente de processos (RPA + IA)',
      'Assistentes virtuais e chatbots corporativos com LLM',
      'Análise preditiva e prescritiva com ML',
      'IA generativa para criação e resumo de conteúdo',
      'Processamento de linguagem natural (NLP)',
      'Visão computacional e análise de imagens',
      'Integração com Claude, GPT-4, Gemini e outros LLMs',
      'MLOps e operacionalização de modelos em produção',
      'Projetos de dados e feature engineering',
      'Consultoria e estratégia de IA para o negócio',
    ],
    benefits: [
      { title: 'Automação Inteligente', description: 'Tarefas repetitivas automatizadas com aprendizado contínuo da IA.' },
      { title: 'Insights Preditivos', description: 'Antecipe tendências e tome decisões baseadas em dados e modelos preditivos.' },
      { title: 'Personalização em Escala', description: 'Experiências personalizadas para clientes e colaboradores sem custo adicional.' },
      { title: 'Vantagem Competitiva', description: 'Projetos de IA que entregam resultados reais e mensuráveis para o negócio.' },
    ],
    icon: 'Bot',
    color: 'from-violet-600 to-fuchsia-500',
    bgColor: 'rgba(124,58,237,0.1)',
  },
]

export const solutionsBySlug = Object.fromEntries(solutions.map((s) => [s.slug, s]))

export const solutionGroups = [
  {
    label: 'Gestão Empresarial',
    items: solutions.filter((s) => ['bpm', 'cpm', 'esm', 'cwm', 'ppm'].includes(s.slug)),
  },
  {
    label: 'Qualidade & Risco',
    items: solutions.filter((s) => ['qms', 'grc', 'erm', 'ehsm'].includes(s.slug)),
  },
  {
    label: 'Sustentabilidade & Ativos',
    items: solutions.filter((s) => ['esg', 'eam', 'ecm', 'slm'].includes(s.slug)),
  },
  {
    label: 'Pessoas & Inovação',
    items: solutions.filter((s) => ['hdm', 'icm', 'plm'].includes(s.slug)),
  },
  {
    label: 'Tecnologia & IA',
    items: solutions.filter((s) => ['pedido-flow', 'ia-first'].includes(s.slug)),
  },
]
